import { create } from 'zustand';
import type { EditorStore, EditorMode, BackgroundType, GradientConfig, EffectsConfig } from '@/types';

const DEFAULT_GRADIENT: GradientConfig = { from: '#6366f1', to: '#a855f7', angle: 135 };
const DEFAULT_EFFECTS: EffectsConfig = {
  shadowType: 'none',
  shadowOpacity: 0.5,
  shadowBlur: 20,
  shadowOffsetX: 0,
  shadowOffsetY: 10,
  brightness: 100,
  contrast: 100,
  saturation: 100,
};

export const useEditorStore = create<EditorStore>((set) => ({
  originalFile: null,
  originalDataUrl: null,
  processedBlob: null,
  processedDataUrl: null,
  rawProcessedDataUrl: null,

  mode: 'view',
  brushSize: 20,
  removalSensitivity: 50,
  zoom: 1,
  canUndo: false,
  canRedo: false,

  backgroundColor: '#ffffff',
  backgroundType: 'transparent',
  backgroundImageUrl: null,
  backgroundGradient: DEFAULT_GRADIENT,
  backgroundBlur: 10,

  effects: DEFAULT_EFFECTS,

  showOriginal: false,

  isProcessing: false,
  processingProgress: 0,
  processingError: null,

  setOriginalFile: (file, dataUrl) => set({
    originalFile: file,
    originalDataUrl: dataUrl,
    processedBlob: null,
    processedDataUrl: null,
    rawProcessedDataUrl: null,
    removalSensitivity: 50,
    canUndo: false,
    canRedo: false,
  }),
  setProcessedBlob: (blob, dataUrl) => set({ processedBlob: blob, processedDataUrl: dataUrl }),
  setProcessedDataUrl: (url) => set({ processedDataUrl: url }),
  setRawProcessedDataUrl: (url) => set({ rawProcessedDataUrl: url }),
  setMode: (mode: EditorMode) => set({ mode }),
  setBrushSize: (brushSize) => set({ brushSize }),
  setRemovalSensitivity: (removalSensitivity) => set({ removalSensitivity }),
  setZoom: (zoom) => set({ zoom }),
  setCanUndo: (canUndo) => set({ canUndo }),
  setCanRedo: (canRedo) => set({ canRedo }),
  setBackgroundColor: (backgroundColor) => set({ backgroundColor }),
  setBackgroundType: (backgroundType: BackgroundType) => set({ backgroundType }),
  setBackgroundImageUrl: (backgroundImageUrl) => set({ backgroundImageUrl }),
  setBackgroundGradient: (backgroundGradient: GradientConfig) => set({ backgroundGradient }),
  setBackgroundBlur: (backgroundBlur) => set({ backgroundBlur }),
  setEffects: (e: Partial<EffectsConfig>) => set((s) => ({ effects: { ...s.effects, ...e } })),
  setShowOriginal: (showOriginal) => set({ showOriginal }),
  setIsProcessing: (isProcessing) => set({ isProcessing }),
  setProcessingProgress: (processingProgress) => set({ processingProgress }),
  setProcessingError: (processingError) => set({ processingError }),
  reset: () =>
    set({
      originalFile: null,
      originalDataUrl: null,
      processedBlob: null,
      processedDataUrl: null,
      rawProcessedDataUrl: null,
      mode: 'view',
      brushSize: 20,
      removalSensitivity: 50,
      zoom: 1,
      canUndo: false,
      canRedo: false,
      backgroundColor: '#ffffff',
      backgroundType: 'transparent',
      backgroundImageUrl: null,
      backgroundGradient: DEFAULT_GRADIENT,
      backgroundBlur: 10,
      effects: DEFAULT_EFFECTS,
      showOriginal: false,
      isProcessing: false,
      processingProgress: 0,
      processingError: null,
    }),
}));
